# Generated by Django 3.1.7 on 2021-03-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
